# /home/liam/.config/tmuxinator/masters.yml

name: masters
# This path is MacOS specific... there is no official desktop app for Box on Linux anyways.
root: ~/Library/CloudStorage/Box-Box/masters

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: writing

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:
  - writing:
      layout: main-horizontal
      panes: 
        - nvim
  - code:
      layout: b95b,269x69,0,0[269x50,0,0,0,269x18,0,51{134x18,0,51,4,134x18,135,51,6}]
      root: ~/Library/CloudStorage/Box-Box/masters/code
      panes:
        - nvim
        - julia
        - jupyter-lab
  - nonlinear:
      layout: main-horizontal
      root: ~/Dropbox/nonlinear-analysis-of-dynamical-systems/
      panes: 
        - nvim
  - bayes:
      layout: main-horizontal
      root: ~/Dropbox/computational-bayesian-statistics/
      panes:
        - nvim
  - notes:
      layout: 5906,269x63,0,0[269x48,0,0,12,269x14,0,49,17]
      root: ~/Dropbox/notes 
      panes:
        - editor:
          # Automatically zoom on this panel on start
          - tmux resize-pane -Z
          - nvim
        # This script will automatically update the index files upon change
        - ./autoindex.sh
  - dotfiles:
      layout: main-horizontal
      root: ~/dev/dotfiles
      panes:
        - 
