theme = "plain"
icons = "awesome"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "net"
format = "{ssid} {signal_strength}"
interval = 5

